# -*- coding: utf-8 -*-
"""10/31_02_공확률.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15C1KlEzNDUT-Wf9R-Z_W_P5Thbfy-ILe
"""

import sys
print(sys.version)

!python  --version

import math
print(math.factorial(5))

def combination_count(n,r):
  return math.factorial(n) //math.factorial(n-r)

print(combination_count(4, 2))

def combination_count(n,r):
  return math.factorial(n) //(math.factorial(n - r)*math.factorial(r) )

print(combination_count(4, 2))

print(combination_count(4, 0))

print("빨간 공 r개 파란공 b개가 들어있는 주머니에서 n개의 공을 꺼낼려고 합니다. \n")

print("뽑힌 공 중 파란 공의 개수를 확률 변수 X라고 했을 때 X의 확률 분포를 나타내시오. ")

#입력 받을 것
#초기화 작업

b =0
r=0
n=0
x=0.0
print("빨간 공의 갯수를 입력하세요.")
test= input()
b=int(test)

print("파란 공의 갯수를 입력하세요.")
test = input()
r = int(test)

print("꺼낼 공의 갯수를 입력하세요.")
test = input()
n = int(test)

sum = 0
avg =0
var =0
for i in range(n+1):
  result = combination_count(r, n-i) * combination_count(b,i) / combination_count(b+r,n)
  sum += result
  avg += result*i

print("P(",i,") =", result)
print("Psum =",sum)
print("avg =", avg)

for i in range(n+1):
   result = combination_count(r, n-i) * combination_count(b,i) / combination_count(b+r,n)
   var += (i-avg) * (i-avg) * result

print("var =",var)

i = 0
print(r)
print(b)
print(n)

result = combination_count(r, n-i)* combination_count(b,i) / combination_count(b+r,n)
sum += result
result = combination_count(4, 3)* combination_count(5,0) / combination_count(9,3)
sum += result