# -*- coding: utf-8 -*-
"""10/31_01_이산확률분포_동전이 앞이 나올 확률.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fu4VPkuwc5DQZIOvqj9PMhTGwOVQuqvY
"""

import sys
print(sys.version)

!python  --version

import math
print(math.factorial(5))

def combination_count(n,r):
  return math.factorial(n) //math.factorial(n-r)

print(combination_count(4, 2))

def combination_count(n,r):
  return math.factorial(n) //(math.factorial(n - r)*math.factorial(r))

print(combination_count(4, 2))

print(combination_count(4, 0))

print("동전을 4번 던져서 n개가 앞이 나올 확률")

print("n을 입력하세요.")
n = int(input())
if n > 4 :
  print("다시 입력하세요.")
  n = input()

P = combination_count(4, int(n))/(2*2*2)
print(P)